//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2_Feb.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Person
    {
        [Display(Name = "ID")]
        public int PersonID { get; set; }

        [Display(Name = "First Name")]
        [Required(ErrorMessage ="First name is required")]
        [StringLength(12)]
        public string First_Name { get; set; }

        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "Last name is required")]
        [StringLength(12)]
        public string Last_Name { get; set; }

        [Required(ErrorMessage = "Email is required")]
        [EmailAddress]
        public string E_mail { get; set; }

        [RegularExpression("((079)|(078)|(077)){1}[0-9]{7}")]
        public Nullable<decimal> Phone { get; set; }

        [Range(18,50)]
        public Nullable<int> Age { get; set; }
        [MaxLength(10)]
        public string Job_Title { get; set; }
        public Nullable<bool> Gender { get; set; }
    }
}
