//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _8_Feb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chair
    {
        public int ChairID { get; set; }
        public string Chair_Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Chair_Desc { get; set; }
        public string img { get; set; }
        public string img2 { get; set; }
        public string img3 { get; set; }
        public string img4 { get; set; }
        public Nullable<bool> inStock { get; set; }
    }
}
